    spring.application.name=laptop-shop


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=laptop_shop_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


cloudinary.cloud-name=dzz3kbuuj
cloudinary.api-key=675364625369594
cloudinary.api-secret=1E3Z-HyZ3DwOP8uQF0FAu0jLYN0

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB